# Generated by Django 2.0.6 on 2018-06-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('film_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('all_shows_today', models.CharField(blank=True, max_length=500, null=True)),
                ('show_start', models.CharField(max_length=500)),
                ('show_end', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=500)),
                ('format', models.CharField(blank=True, max_length=500, null=True)),
                ('genres', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
                ('actors', models.CharField(max_length=1000)),
                ('trailer', models.CharField(max_length=500)),
                ('poster', models.CharField(max_length=500)),
                ('schedule', models.CharField(blank=True, max_length=500, null=True)),
                ('already_out', models.IntegerField()),
            ],
        ),
    ]
