# Generated by Django 2.0.6 on 2018-06-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_bot', '0002_auto_20180611_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='schedule',
        ),
    ]
